name: Initialize Hugo Site

on:
  workflow_dispatch:  # 允许手动触发

jobs:
  initialize:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: recursive  # 确保主题子模块也被检出
        
    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: 'latest'
        extended: true
        
    - name: Run initialization script
      run: python script/initialize.py
      env:
        GH_TOKEN: ${{ secrets.ACTIONS_TOKEN }}
        
    - name: Deploy to GitHub Pages
      run: |
        cd public
        git init
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git checkout -b main  # 确保使用 main 分支
        git add .
        git commit -m "Initial commit"
        git push --force "https://${{ secrets.ACTIONS_TOKEN }}@github.com/jwj330/jwj330.github.io.git" main
