name: Publish New Post

on:
  workflow_dispatch:  # 允许手动触发

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: recursive  # 包含主题子模块
        
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        
    - name: Install Hugo
      run: |
        sudo apt-get update
        sudo apt-get install hugo
        
    - name: Generate new post
      run: python script/post.py
      
    - name: Build and deploy
      run: |
        hugo --minify
        cd public
        git init
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git add .
        git commit -m "New post: $(date +'%Y-%m-%d %H:%M:%S')"
        git push --force "https://${{ secrets.ACTIONS_TOKEN }}@github.com/jwj330/jwj330.github.io.git" main
